GET http://localhost:3000/posts
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGl5dXNoIiwiaWF0IjoxNzU0ODE1NTI0LCJleHAiOjE3NTQ4MTU4MjR9.V8mFqamAZzJJRxMyJTgQlFzqYwWIt0Br-0R89cjP4Rk
 

###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGl5dXNoIiwiaWF0IjoxNzU0ODE1NTI0fQ.XVJaFNPMn7Q2RaKpSP-_YtdNBxn5madeb7VyuZJZcvI"
}

###
POST http://localhost:4000/token Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGl5dXNoIiwiaWF0IjoxNzU0ODE1NTI0fQ.XVJaFNPMn7Q2RaKpSP-_YtdNBxn5madeb7VyuZJZcvI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Piyush"
}